service: awsLambdaAPIAssessment
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-southeast-2
functions:
  exercise1:
    handler: src/exercise1.handler
    environment: 
      API_ACCESS_TOKEN: ${ssm:/apiAccessToken}
      ENVIRONMENT: ${ssm:/environment}
    events:
      - http:
          path: /user
          method: get
  exercise2:
    handler: src/exercise2.handler
    environment: 
      PRODUCTS_URL: ${ssm:/productsUrl}
      SHOPPING_HISTORY_URL: ${ssm:/shoppingHistoryUrl}
      API_ACCESS_TOKEN: ${ssm:/apiAccessToken}
      ENVIRONMENT: ${ssm:/environment}
    events:
      - http:
          path: /sort
          method: get
  exercise3:
    handler: src/exercise3.handler
    environment: 
      PRODUCTS_URL: ${ssm:/productsUrl}
      SHOPPING_HISTORY_URL: ${ssm:/shoppingHistoryUrl}
      API_ACCESS_TOKEN: ${ssm:/apiAccessToken}
      TROLLEY_CALCULATOR_URL: ${ssm:/trolleyCalculatorUrl}
      ENVIRONMENT: ${ssm:/environment}
    events:
      - http:
          path: /trolleyTotal
          method: post